name: virreport
channels:
  - bioconda
  - conda-forge

dependencies:
## conda-forge packages
  - conda-forge::biopython=1.81
  - conda-forge::pandas=2.0.2
  - conda-forge::pigz=2.6
  - conda-forge::libwebp=1.3.0
  - conda-forge::matplotlib=3.7.1  
## bioconda packages
  - bioconda::fastqc=0.12.1
  - bioconda::cutadapt=4.4
  - bioconda::bcftools=1.17
  - bioconda::umi_tools=1.1.4
  - bioconda::fastp=0.23.3
  - bioconda::bowtie=1.3.1
  - bioconda::velvet=1.2.10
  - bioconda::spades=3.15.5
  - bioconda::cap3=10.2011
  - bioconda::blast=2.14.0
  - bioconda::bedtools=2.31.0
  - bioconda::emboss=6.6.0
  - bioconda::picard=3.0.0
  - bioconda::samtools=1.17
  - bioconda::perl-bioperl=1.7.8
